apiVersion: v1
kind: Service
metadata:
  name: reddit-classifier-service
spec:
  selector:
    app: reddit-classifier
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
    protocol: TCP